# Generated by Django 4.1.5 on 2023-03-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdl',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='mdl',
            name='attach',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='mdl',
            name='subject',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='mdl',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='mdl',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mdl',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
