from mega import Mega
from tkinter import filedialog
mega = Mega()
#username = input("Enter username - ")
#password = input("Enter password - ")
m = mega.login("rohankumarchadha@gmail.com","Rohan.007")
details = m.get_user()
quota = m.get_quota()
space=m.get_storage_space(mega=True)
#files=m.get_files()
#print(files)
#upl=m.upload(filedialog.askopenfilename())
#uplink=m.get_upload_link(upl)
#print(uplink)
#exp=m.export("sample.txt")
#file1=m.download(exp)
#print(exp)
print(details)
print(quota)
print(space)
#files = m.get_files()
#print(files)
#file = m.upload("sample.txt")
#newfile = m.download("sample.txt")