# Generated by Django 4.1.5 on 2023-03-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='file',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
